# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-06 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='\u6807\u9898')),
                ('body', models.TextField(verbose_name='\u5185\u5bb9')),
                ('timestamp', models.DateTimeField(verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u968f\u60f3',
                'verbose_name_plural': '\u968f\u60f3',
            },
        ),
    ]
