# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-06 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170906_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogsWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='\u6807\u9898')),
                ('body', models.TextField(verbose_name='\u5185\u5bb9')),
                ('timestamp', models.DateTimeField(verbose_name='\u7f16\u8f91\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u535a\u5ba2\u6587\u7ae0',
                'verbose_name_plural': '\u535a\u5ba2\u6587\u7ae0',
            },
        ),
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.DeleteModel(
            name='EmailVerifyRecord',
        ),
    ]
